### ISSUE TITLE
not an issue, how to change unite to mA ?

### ISSUE THREAD

**Issue by ens4dz** [kolinger/rd-usb#16]
how to change graph unite from A to milliAmps ?
thanks for this great project.

**Comment by kolinger** [comment]
Hello, there is no such option. Current is available only in A. But it can be added if you think this is needed.

**Comment by ens4dz** [comment]
I think it is useful to measure current for Iot modules (arduino,esp32..)

**Comment by kolinger** [comment]
Alright, I did add mA as new axis option for graph. Now you can select Current (A) or Current (mA) as you wish. You can download new version [here](https://github.com/kolinger/rd-usb/releases/tag/1.8.0). Does it solve your need?

**Comment by ens4dz** [comment]
![2021-11-01 17_08_33-RD-USB v1 8 0](https://user-images.githubusercontent.com/10385950/139703440-1390cab9-476e-4056-9e9f-3ba73035f393.png)
 yes it's better now thanks a lot
there are some worried thing, graph didn't display correctly until press **apply** every 5s or so ! , in Amps it's display is fine.

**Comment by kolinger** [comment]
I see, live update is broken and only history works. Try [1.8.1](https://github.com/kolinger/rd-usb/releases/tag/1.8.1).

**Comment by ens4dz** [comment]
Awesome support, many thanks  !
it works now.
