### ISSUE TITLE
Connecting to multiple devices

### ISSUE THREAD

**Issue by sweichbr** [kolinger/rd-usb#44]
Is there a way to connect to multiple devices at the same time?  Could I run two instances of the app (and if so, how can I change the Port number to have them both run)?

**Comment by kolinger** [comment]
I updated readme - there is now extra section [Multiple instances](https://github.com/kolinger/rd-usb?tab=readme-ov-file#multiple-instances), check it out and let me know if it's sufficient for you needs.

**Comment by sweichbr** [comment]
Worked as instructed.
